### ISSUE TITLE
[Orchestrators] iterators and organizers

### ISSUE THREAD

**Issue by kofronpi** [adomokos/light-service#105]
Hey,

Really happy about orchestrators so far ! 

I just noticed that the context passed to an organizer from an iterator didn't include the singularized key (:link in my case), but did for an action...

I read the acceptance spec but it only test it with an action too. I will take a look to write another spec.

Have a good day

**Comment by adomokos** [comment]
That is possible. Can you create a spec to prove this? Thank you!

**Comment by kofronpi** [comment]
I wrote some specs to mess around and couldn't reproduce, then when I removed the logger line in my code it worked:

```
module Orchestrators
  class FullETL
    extend LightService::Orchestrator

    def self.run(context)
      with(context).reduce([
              ETL::RetrieveConnectionInfoAction,
              iterate(:links, [
                ETL::ImportLastMonthlyStock
              ])
            ])
    end
  end
end


module ETL
  class ImportLastMonthlyStock
    extend LightService::Organizer

    def self.call(context)
      LightService::Configuration.logger.info "Iterating on link #{context.link}"
      with(context).reduce(
          ETL::PullFileFromAPI,
          ETL::UnzipFile,
          ETL::ImportMonthlyStockCSV
        )
    end
  end
end
```
Isn't `context.link` supposed to be accessible there for logging ?

**Comment by adomokos** [comment]
The `context.link` is a helper to make the code readable. Specifying `expects :link` would generate the accessor method.

Have you tried `#{context[:link]}`? I believe that should work.

**Comment by kofronpi** [comment]
I found a workaround, I'm closing this until I can gather more info if there is effectively a bug hidden here.
