### ISSUE TITLE
Removing Rollback Feature

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#111]
I added the [rollback](https://github.com/adomokos/light-service/#action-rollback) feature to LS a while ago. I have not used it since. Is this something people are using?

I am considering removing it in the next major version.

**Comment by gee-forr** [comment]
Hey @adomokos - please keep it around. I use it, and rely heavily on it.

(P.S - thanks so much for this gem, it's helped me level up my code big time)

**Comment by adomokos** [comment]
@gee-forr, thanks for your reply. I have not used this feature much. How do you use it? What do you use it for? Can you provide a brief description? Thank you!

**Comment by gee-forr** [comment]
In my particular use case, we're provisioning a product that needs to be spun up via an API. After that, we have to create an invoice using another API to the sales system, and then send off a few notifications, etc.

If any of those steps fail, we need to remove the db records, undo the product provisioning, or nullify the invoice. 

Without having rollbacks, it would be next to impossible to have composable business logic.

Another slightly interesting hack I've done is to have a service declared as the very first service in the organiser list that is effectively a NOOP, and only has a rollback action that sends a slack notification. For ultra critical services that should never have to be rolled back, this is called last detailing possible reasons for the rollback.

Hope this helps.

**Comment by adomokos** [comment]
It does, thanks for the feedback.
I built this functionality a while back and never used it in the project I was working on at that time.

It's hard to see how this piece of code (the gem itself) is being used in the wild. Every bit helps.

Thanks! 👍
