### ISSUE TITLE
Possible thread safety issue

### ISSUE THREAD

**Issue by bwvoss** [adomokos/light-service#114]
I'm not sure how to confirm this, but there are suspicions about this line: https://github.com/adomokos/light-service/blob/f34954a2c1b8f51e7a1f04363563e3a6b097c266/lib/light-service/orchestrator.rb#L9 not being thread safe.  Anybody have experience in this?

**Comment by adomokos** [comment]
Can you please provide more context? Maybe a spec that reproduces this issue?
