### ISSUE TITLE
Orchestrator not raising failing context

### ISSUE THREAD

**Issue by redjoker011** [adomokos/light-service#128]
Hi i just want to ask why orchestrator does not raise failing context unlike organizers? is this intended or is there another way to identify whenever an organizer/action fails when executing steps in orhcestrator?

**Comment by adomokos** [comment]
Could you please provide an example? A failing spec would be the best.

Just an FYI, I am planning on removing orchestrators from LightService and adding all Orchestrator functionality to Organizers.

**Comment by redjoker011** [comment]
The issue that i've facing is when you mix actions and organizers inside orchestrator steps, orchestrator only catch failing actions but when failing actions are inside organizers, orchestrator does not catch failing context which results the orchestrator to success even with failing context. Also orchestrator only return response from actions but response from organizers are missing. Am i the one experiencing this issue? Thanks for response

**Comment by adomokos** [comment]
@redjoker011: I added a spec to prove the functionality of failed context from an Organizer in an Orchestrator spec in PR #131.

Can you please alter the code I started to show where the failure is not bubbling up?

**Comment by adomokos** [comment]
@redjoker011 - is this still an issue?

**Comment by redjoker011** [comment]
Yeah the issue still persist so i decided to use Organizer instead. Also since you've mention that you would remove Orchestartors in future , maybe we can close this issue since it is Orchestartor related. Thanks for the time

**Comment by adomokos** [comment]
K, I'll close it for now. 0.9.0 will be released very soon, I am testing it with our apps.
