### ISSUE TITLE
Logger in Orchestrator

### ISSUE THREAD

**Issue by sphynx79** [adomokos/light-service#134]
when i use LightService::Organizer i activate the logger:
LightService::Configuration.logger = Logger.new(STDOUT)
and i see the log work fine
```ruby
module AppMeter
  class Meter
     extend LightService::Organizer

    def self.run()
      with({}).reduce(
        [
          InitAutoit,
          InitBrowser,
          MinimizeDos,
          OpenSite,
          ClickConsenti
        ]
      )
    end
end
end
```
but in when i use Orchestrator i don't see nothing
```ruby
module AppMeter
  class Meter
     extend LightService::Orchestrator

    def self.run()
      with({}).reduce(
        [
          InitAutoit,
          InitBrowser,
          MinimizeDos,
          OpenSite,
          ClickConsenti,
          iterate(:links, [DownloadFiles])
        ]
      )
    end
end
end
```
my program work fine but i don't see the log.

**Comment by sphynx79** [comment]
I have also tried to use branch 1.0 but i saw that iterator it is not implemented yet :(

**Comment by adomokos** [comment]
1.0 branch is highly experimental at this point. If anything else, give #132 branch a try. Early feedback would be highly appreciated.

**Comment by adomokos** [comment]
Is this still an issue? Can I close this? I am planning on releasing #132 in the next 2 weeks once I had the chance of testing it with our apps.

**Comment by sphynx79** [comment]
Yes you can close this issue, because in this moment i use Orchestrator and i implement my logger.

Some news about new version???

**Comment by adomokos** [comment]
Yep, 0.9.0 is coming out shortly with #132. We've been testing it in Production for a few days now. I'd like to release that by the end of this week. Cheers!
