### ISSUE TITLE
Accessing context values directly in executed block

### ISSUE THREAD

**Issue by robwilliams** [adomokos/light-service#135]
In the README there is an example action:

```ruby
class CalculatesOrderTaxAction
  extend ::LightService::Action
  expects :order, :tax_percentage

  executed do |context|
    order.tax = (order.total * (tax_percentage/100)).round(2)
  end
end
```

This doesn't actually work, `order` has to be accessed through context, it's not available directly in the executed block.

I've actually hit this issue myself and it would be nice to be able to reference the items in the context that have been defined with `expects` without the prefix..

My workaround at the moment is to assign the variables myself:

```ruby
class CalculatesOrderTaxAction
  extend ::LightService::Action
  expects :order, :tax_percentage

  executed do |context|
    order = context.order
    tax_percentage = context.tax_percentage

    order.tax = (order.total * (tax_percentage/100)).round(2)
  end
end
```

Do you think this kind of sugar is worth adding?

**Comment by adomokos** [comment]
Thank you for catching an error in the README example! I'll fix it today.

I don't mind accessing variables from the context by referring to it via the context, that way I know where that value is coming from. Setting it globally might go against the idea of LightService, where I wanted to decouple state from behavior.

**Comment by adomokos** [comment]
See this [commit](https://github.com/adomokos/light-service/commit/ea114045250194599e599d15a5076ed84b43e70f) to fix it. Please submit a PR if you think README needs more TLC.

Thanks again!
