### ISSUE TITLE
Remove Key Aliases

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#136]
At one point, we needed key aliasing for our actions to avoid 1 line Actions. You can find more about it [here](https://github.com/adomokos/light-service#key-aliases).

Now that we have Orchestrator functionality in Organizers, I think this feature is obsolete. We could accomplish the same thing with an `execute` actions.

So instead of doing this:

```ruby
class SomeAction
   aliases :my_key => :key_alias
end
```

We could do this:

```ruby
class SomeOrganizer
  extend LightService::Organizer

  def self.call(id)
    with(:id => id).reduce(actions)
  end

  def self.actions
    [SomeAction1,
     SomeAction2,
     execute(->(ctx) { ctx[:key_alias] = ctx[:my_key] }),
     AnotherAction]
  end
end
```

See how the execute block now is responsible for aliasing.

Let me know if you're *NOT* OK with deprecating (and eventually removing in 1.0) key aliasing.

**Comment by adomokos** [comment]
A deprecation warning would be a great start for this, before the feature is removed.

**Comment by gee-forr** [comment]
Only saw this now... just want to point out that I do use key_aliases, and it would be great if they could stick around, especially as Orchestrators are now deprecated...

**Comment by adomokos** [comment]
I'll leave this, but before hooks or even a simple `execute` block could be used to this.
I don't think there is enough support to remove it, I'll keep it in there.
