### ISSUE TITLE
LightService::Organizer in class instance

### ISSUE THREAD

**Issue by sphynx79** [adomokos/light-service#137]
Hi,

i need to use organizzer in instance class, i try this

```ruby
class Test 
extend LightService::Organizer

def call
    with({}).reduce(
        Hello
    )
end
```

but i receive undefined method `with' for ...

I try also use 
```ruby
include LightService::Organizer
```
but i receive :
DEPRECATION WARNING: including LightService::Organizer is deprecated. Please use `extend LightService::Organizer`

My question is how can instance one class ad use organizzer inside this class.

Thanks

**Comment by adomokos** [comment]
LightService Organizers and Actions were never created to be instantiated, I wanted to keep state and behavior separate. State is flowing through the actions and mutated by the actions.

I would suggest calling your organizer from the object instance like this:

```ruby
class SomeOrganizer
  extend LightService::Organizer

  def self.call(ctx)
    with(ctx).reduce([
      FirstAction,
      SecondAction
    ])
  end
end

# And call it from here

class MyClass
  def do_something
    SomeOrganizer.call({:user => user})
  end
end
```

Would this work?

If not, could you provide more context?

**Comment by sphynx79** [comment]
I have modified your code 

```ruby
module LightService
  module Organizer
    def self.extended(base_class)
      base_class.extend ClassMethods
      base_class.extend Macros
    end

    def self.included(base_class)
      base_class.include ClassMethods
      base_class.include Macros
    end
```

and  now i can you also with instance method

Thanks.

You can close this issues

**Comment by adomokos** [comment]
Sounds good, thanks!
