### ISSUE TITLE
fail_and_return does not allow for options (error_code)

### ISSUE THREAD

**Issue by jwright** [adomokos/light-service#154]
I would like to call `fail_and_return` with an `error_code` option. (i.e. `context.fail_and_return!("This did not work", error_code: 400).

This does not work because of the call to `throw(:jump_when_failed, *args)` is called and `throw` only takes a 1..2 arguments.

In addition, I think allowing `options` like `fail!` does would make for a more consistent api.

Since the `catch` for `:jump_when_failed` is not doing anything with those arguments, I feel the code should simply not pass along the `args`. Thoughts?

Let me know if you agree with this and I'd be happy to submit a PR for this!

Thanks for all the work you do on this. :heart:

**Comment by adomokos** [comment]
I have never used the `error_code` feature myself. I wonder if we could build something more generic, and an options argument might be a good replacement for it.

**Comment by gee-forr** [comment]
Chiming in here... I use the error code feature extensively... mainly for returning a pertinent code to be used as an HTTP status code. If you do decide to deprecate the feature, please could you do so with a version that emits warnings first?

Also, +1 on @jwright's comment. I really appreciate the work you've done on this gem. It's made my code significantly better. Thank you.

**Comment by adomokos** [comment]
@gee-forr: thanks for your input. I'd like to find a way to provide an option to make error code a bit more abstract or general, maybe as an "options" argument. I am not sure yet.
You are the second person who mentioned this feature is being used by someone.

Btw, whenever I change or remove things, I have at least a year of warning prior to making the move. Just try to use the latest version and fix the warning. :wink:

**Comment by jwright** [comment]
I do use `error_code` for the front-end to sort of "group errors". I usually use http codes for stuff like "not authenticated", etc. I like the idea of `options` instead of an `error_code` since the consumers could add `error_code` to the options if they feel like it.

**Comment by rvirani1** [comment]
I just ran into this today. It would be great to have something like `options` as a more generic option.

**Comment by sobrinho** [comment]
@adomokos this can be closed due to #168.

**Comment by adomokos** [comment]
Thanks! Closing.
