### ISSUE TITLE
Using an Organizer within another Organizer

### ISSUE THREAD

**Issue by matthewheath** [adomokos/light-service#160]
I'm using an Organizer within another, like so:

```
module Orders
  class PlacesOrder
    extend LightService::Organizer

    def self.call(order)
      with(order: order).reduce(
        [
          Orders::Taxes::CalculatesTax
        ]
      )
    end
  end
end
```

with `Orders::Taxes::CalculatesTax` being its own Organizer:

```
module Orders::Taxes
  class CalculatesTax
    extend LightService::Action
    extend LightService::Organizer

    executed do |context|
      order = context.fetch :order

      with(order: order).reduce(
        [
          ChecksTaxCollectionNeededAction,
          LooksUpTaxPercentageAction,
          CalculatesOrderTaxAction
        ]
      )
    end
  end
end
```

however I am getting `DEPRECATION WARNING: The <Orders::Taxes::CalculatesTax> class is an organizer, its entry method (the one that calls with & reduce) should be named `call`. Please use Orders::Taxes::CalculatesTax.call going forward.` when the root Organizer runs. 😞 

Is there a better way of handling this sort of workflow?

**Comment by adomokos** [comment]
Thanks for reporting this.

I have not tested this scenario before, as an action should not be mixed with Organizer functionality. 

Would this work for you?
```ruby
module Orders::Taxes
  class CalculatesTax
    extend LightService::Action
    extend LightService::Organizer

    executed do |context|
      order = context.fetch :order

      with(order: order).reduce(actions)
    end

    def self.actions
        [
          ChecksTaxCollectionNeededAction,
          LooksUpTaxPercentageAction,
          CalculatesOrderTaxAction
        ]
    end
  end
end

module Orders
  class PlacesOrder
    extend LightService::Organizer

    def self.call(order)
      with(order: order).reduce(
        [
          Orders::Taxes::CalculatesTax.actions
        ]
      )
    end
  end
end
```

Just reuse the action sequence from one organizer in the other. I [added](https://github.com/adomokos/light-service/pull/161) this test to prove it.

**Comment by matthewheath** [comment]
This works perfectly, thank you @adomokos! I will use this design in the future. 👍

**Comment by kbleabres** [comment]
Hi @adomokos ! I am encountering the same problem, but the solution above wouldn't work for me. 
I am using an `Organizer` within an `Organizer` like so:

```ruby
class One
  LightService::Organizer

  def self.call(data)
    with(data: data).reduce(
      SecondAction,
      ThirdAction,
      FourthAction
    )
  end
end

class ThirdAction
  LightService::Organizer
  LightService::Action
  expects :data, :stuff_from_second_action,
  promises :stuff_for_fourth_action

  executed do |ctx|
    ctx.stuff_for_fourth_action = ctx.data.map do |object|
      with(object: object).reduce(
        ThreePtOne,
        ThreePtTwo,
        ThreePtThree
      ).items
    end
  end
end
```
It's because I'm processing array contents in the `ThirdAction`

I'm getting
```ruby
DEPRECATION WARNING: The <ThirdAction> class is an organizer, its entry method (the one that calls with & reduce) should be named `call`. Please use ThirdAction.call going forward. (called from block (2 levels) in <class:ThirdAction> at fdsfdsf
```

Is this bad practice? Should I open a new issue?

**Comment by adomokos** [comment]
@kbleabres - When I created LightService, my thinking was that Organizers call Actions, and Actions are at the bottom of the call stack, Actions can't call another Action or Organizer to avoid spaghetti code.

With the introduction of orchestrator functionality we introduced higher-level constructs that can navigate around actions, this way more organizing logic can be pushed into Organizers (like conditionals, iterators, callbacks).

In your example `class One` looks good. However, `ThirdAction` should be either an Action or an Organizer, not both.

Are `ThreePtOne`, `ThreePtTwo` Action classes? If they are, can you elevate that logic into the `One` organizer? Also, the library does not support `map`, so you must use iterators if your data is traversable.

I would write something like this:

```ruby
class One
  LightService::Organizer

  def self.call(data)
    with(data: data).reduce(
      SecondAction,
      iterate(:items [
        ThreePtOne,
        ThreePtTwo,
        ThreePtThree
      ]),
      FourthAction
    )
  end
end
```

Then the iterator could put something in the context to simulate `map` functionality.
I realize map here, but I also don't want to create a higher-level language.

Also, the benefit is that you don't need to drill deeper, you can just look at the `One` organizer, and that should tell you the story right there without going into another Organizer.

Let me know if that wouldn't work for you.
