### ISSUE TITLE
Feature idea:  rename executed to more concise word

### ISSUE THREAD

**Issue by KelseyDH** [adomokos/light-service#171]
Nice DSL -- but the repeated innovations of `executed` seem to pollute the readability of the code a bit, for what is essentially boilerplate.

I would love to see `executed` get changed into a more concise word like `run`.  E.g.:

```ruby
class ProvidesFreeShippingAction
  extend LightService::Action
  expects :order

  run do |ctx|
    if ctx.order.total_with_tax > 200
      ctx.order.provide_free_shipping!
    end
  end
end
```

or `step`.  E.g.:

```ruby
class ProvidesFreeShippingAction
  extend LightService::Action
  expects :order

  step do |ctx|
    if ctx.order.total_with_tax > 200
      ctx.order.provide_free_shipping!
    end
  end
end
```

**Comment by adomokos** [comment]
LS was slightly influenced by the [Command](https://en.wikipedia.org/wiki/Command_pattern) design pattern. That's why I left it `execute`. It has not bothered me so far.

We also call orchestrator functions `run`.

**Comment by adomokos** [comment]
I am proposing closing this issue. Thoughts?

**Comment by sobrinho** [comment]
@adomokos this can be closed ;)

**Comment by adomokos** [comment]
Thanks! Closing.
