### ISSUE TITLE
Yard Documentation to code write with light-service

### ISSUE THREAD

**Issue by sphynx79** [adomokos/light-service#186]
Hello excuse me, I would like to be able to comment on my code and then create the documentation with yards, and have an integration with Solargraph, but how can I comment on the code for example to make him understand the parameters that he expects in input my action and what it returns.
Thanks

**Comment by adomokos** [comment]
Sorry for the delayed response on my side.

Are you trying to comment on your code? On LightService's source code?
Is this still an issue?

**Comment by gee-forr** [comment]
@sphynx79 for actions, simply document the class. You will need to manually add the expects and promises as neither YARD nor Solargraph will know to look for those macros.

For organizers, you can document the call action. Depending on how you define its params, you might need to expand on the too.

**Comment by adomokos** [comment]
I am proposing closing this issue. @sphynx79 - did you get your answer?

**Comment by sphynx79** [comment]
Yes you can close this issue. 
Many thanks
