### ISSUE TITLE
Running actions in jobs

### ISSUE THREAD

**Issue by Haegin** [adomokos/light-service#202]
We're looking at using this to coordinate integrations with several external APIs. To get the necessary data back involves several calls and to guard against network issues etc we need to run each of the API requests inside jobs. Is there any way to run an action within a job and have it call the next action with the context as a follow-on job using Light Service?

**Comment by adomokos** [comment]
What jobs are you referring to? Sidekiq? Resque? Maybe Rails?

**Comment by Haegin** [comment]
We're using Delayed::Job via ActiveJob, but I imagine the approach would be the same for any of the above.

**Comment by adomokos** [comment]
We've used LS with Resque to call APIs and persist data similar to how you described it. Resque workers picked up the payload, invoked a LS organizer with that data, and called a series of actions. Would that work for you?

**Comment by gee-forr** [comment]
@Haegin we have similar use cases. Maybe our approach could be useful to you?

Our jobs are extremely thin wrappers around our LS code, so they contain no logic, except for calling the organizer, and then failing the job by throwing an exception if `outcome.failure?`

In fact - we don't actually have `_job.rb` files anymore... We build our organizers that need to be run via a job system like so:

```ruby
  class MyReportOrganizer < ApplicationJob # NOTE: Inherits from ApplicationJob
    extend LightService::Organizer       # as well as extending ls-org

    queue_as :default

    def self.call(payload)
      with(date_range: payload[:date_range], email: payload[:email])
        .reduce(actions)
    end

    def self.actions
      [
        Reports::CollectRawData,
        Reports::WriteSpreadsheet,
        Reports::EmailReport,
      ]
    end

    def perform(start_date_string, end_date_string, email)
      date_range, email = hydrate(start_date_string, end_date_string, email)

      outcome = MyReportOrganizer.call(date_range: date_range, email: email)

      raise RuntimeError("Unable to process report.") if outcome.failure?

      true
    end

    def hydrate(start_date_string, end_date_string, email)
      start_date = Date.parse(start_date_string)
      end_date   = Date.parse(end_date_string)
      date_range = (start_date..end_date)

      [date_range, email]
    end
  end
```

So, what we've got here is a hybrid organizer/job that allows us to call it in the traditional manner from a controller, rake task, with rich objects etc and have it run synchronously, or call it like so:

```ruby
MyReportOrganizer.perform_later(a_bunch, of_primitive, objects_here)
```

and it will take those primitives (which some job systems require), hydrate them into rich objects that are required for synchronous calling, and then run the organizer, failing it with an exception (to ensure a retry) if the job is a `failure?`.

Hope this helps.

**Comment by gee-forr** [comment]
@adomokos - lemme know if you want me to update the readme with this as an advanced usage example...

**Comment by adomokos** [comment]
@gee-forr - that's exactly how I'd do it.
I wouldn't add it to the main README.md, but having an entry with the comment (and code example) you provided in the [wiki](https://github.com/adomokos/light-service/wiki) would be helpful.

**Comment by adomokos** [comment]
I'll close this issue once the entry is created in the wiki.

**Comment by gee-forr** [comment]
@adomokos - sorry man, been really busy... this is still on my todo to add to the wiki

**Comment by adomokos** [comment]
I'll close it once it's in the wiki.

**Comment by gee-forr** [comment]
OK - wiki article is finally up: https://github.com/adomokos/light-service/wiki/Running-Light-Service-organizers-and-actions-in-jobs

**Comment by adomokos** [comment]
Thank you so much for adding that page to the Wiki, @gee-forr, closing this issue. 👍
