### ISSUE TITLE
Help testing LS release candidate

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#221]
I have not been working on large-scale Ruby apps (or I should say professionally) for 2-3 years now.

I would need someone (or even more than one person/project) who could help me test a release candidate with an app.
I will prepare an RC branch, and I'd need you to update your `Gemfile` to point to that branch and run your tests, maybe run the app with it for a few days (1 week) to make sure everything works OK.

Can you please help with this?

**Comment by gee-forr** [comment]
@adomokos - I've got many large test suites that exercise LS. Happy to run my tests against any RCs

**Comment by adomokos** [comment]
Thank you @gee-forr. Whatever is in `main` will be released, so if you want to switch to the main branch, I think we should be good. That's what I did when I had access to a large Ruby application.

**Comment by gee-forr** [comment]
OK - I've tested `main` against two large codebases that make heavy and diverse use of LS - all specs that go anywhere near LS as passing as normal.

**Comment by adomokos** [comment]
Thank you, I'll release a new version shortly.

**Comment by gee-forr** [comment]
howdy @adomokos :) gentle nudge re: a release when you have a gap :)

**Comment by adomokos** [comment]
I know, thanks for the nudge. I'll do it today.
