### ISSUE TITLE
Why this gem add activesupport as runtime dependency?

### ISSUE THREAD

**Issue by zw963** [adomokos/light-service#226]
I want to switch to light-service from interactor,  because it missing some useful feature, e.g. limit the pass in args to specified name, type, but i found light-service, and active_interaction, both of them need activesupport, but i never use it on my project, i don't want introduce any rails dependency, so, leave this question here, thank you.

**Comment by gee-forr** [comment]
Hi @zw963 

LightService does not pull in all of rails. It only uses ActiveSupport, which is also a dependency that Rails has.

In fact, LS only uses these parts of ActiveSupport: `active_support/core_ext/string` and active support deprecation functionality to output deprecation warnings.

It's used in places like this:

* lib/light-service/localization_adapter.rb:41
* lib/light-service/organizer/iterate.rb:11
* and probably a few other places...

I'm sure that LS could probably get away with not using AS and building its own string parsing methods, but why go through the hassle of that when AS does a great job already?

Hope this helps, and to confirm - by using LS, you will not be introducing Rails into your project. You will be introducing a dependency that happens to also be used by Rails.

**Comment by zw963** [comment]
> LightService does not pull in all of rails. It only uses ActiveSupport, which is also a dependency that Rails has.

Yes, maybe describe not so accuracy, what i means is not pull in activesupport,  active_interaction use this too, i never use any functionality of it. in fact , i thought the reason not use activesupport is, it hack too many core ext to ruby builtin class.

for this gem, if use only a little functionality, but pull in a big gem into project, this is not good anyway.

following is a quick search result.

https://github.com/davydovanton/stop_active_support_anywhere

**Comment by gee-forr** [comment]
Thanks for the feedback :)

I went through the link you provided - unfortunately, they don't offer any alternatives for the string extensions LS requires.

They do offer an alternative for handling deprecations which is something I would like to look at working on for LS.

That being said - I would encourage you to issue a PR that will remove the dependency on AS - we would really appreciate it.

**Comment by adomokos** [comment]
Thanks, @gee-forr for chiming in.

I've been unhappy about having AS dependency in LightService for a long time. [It was introduced](https://github.com/adomokos/light-service/pull/55/files) a long time ago, and I think we used it for some one-off functionality that I've tried to remove, but people are still using it. 🤷‍♂️ 

I thought there was an issue to remove the AS dependency, but I can't find it.

At any rate, if anyone sends a PR where the AS dependency is removed, I'll merge it.

Thanks!

**Comment by zw963** [comment]
> I went through the link you provided - unfortunately, they don't offer any alternatives for the string extensions LS requires.

In fact, some of string functionality can be refer from sequel gem.

https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/inflections.rb#L144-L149

**Comment by adomokos** [comment]
@zw963 Are you proposing swapping the AS gem dependency with the `sequel` gem?

**Comment by zw963** [comment]
> @zw963 Are you proposing swapping the AS gem dependency with the `sequel` gem?

No, what i means is we can copy code from sequel gem. anyway, sequel code is more better than rails from my point.

even, dependency sequel is better than dependency activesupport, former no any runtime dependency, activesupport pull in too many current not so useful functionality, and gems, e.g.  Do we use `i18n` and `tzinfo` gem which pull in by activesupport?

**Comment by zw963** [comment]
I am current working on switch from interactor  to [service_actor]https://github.com/sunny/actor, it more simple than 
this gem after take a quick look, maybe i will switch to light-service some day if i need a more powerful service object.

Thank you.

**Comment by adomokos** [comment]
> No, what i means is we can copy code from sequel gem.

Oh, I see. Yeah, I am all for it! Send a PR to kill AS dependency, and I'll merge it.

**Comment by zw963** [comment]
> > No, what i means is we can copy code from sequel gem.
> 
> Oh, I see. Yeah, I am all for it! Send a PR to kill AS dependency, and I'll merge it.

Okay, i can try one or two days later. though, maybe i should study use this gem first. :smile:

**Comment by zw963** [comment]
I saw a old article i saw before, it explain why we don't want ActiveSupport too.

https://rosenfeld.herokuapp.com/en/articles/ruby-rails/2017-05-01-feeling-alone-in-the-ruby-community-and-replacing-rails-with-roda

maybe i can help on remove it, but, for now, there is no reason to switch to this gem except this issue.

https://github.com/sunny/actor/issues/53

maybe we keeping this issue open util it done.

**Comment by adomokos** [comment]
ActiveSupport no more, closing this issue.
