### ISSUE TITLE
around for Actions

### ISSUE THREAD

**Issue by alitsiya** [adomokos/light-service#228]
I have a code with legacy [interactor](https://github.com/collectiveidea/interactor) library (library haven't been updated since Dec. 2019) that I want to convert to a light-service actions. But there is an important piece is missing. Interactor allows you to have an `around` [hook](https://github.com/collectiveidea/interactor/blob/57b2af9a5a5afeb2c01059c40b792485cc21b052/lib/interactor/hooks.rb#L51) for a single service object vs LightService has `around_each` hook on Organizer, but not on a single Action.

I can customize Action inside my app and add `around` to MyBaseAction like this:
```
class MyBaseAction
  extend ::LightService::Action
  include MyHooks

 around :set_data_dog_traces

end
```

 But was wondering if you would consider having `around` hook for a single Action.

**Comment by adomokos** [comment]
Hello @alitsiya!

When we added the `around_each` Organizer function, we believed that Actions should not be called individually, they should be part of an Organizer. In fact, I don't recall ever creating a single-action Organizer, I always started with two actions.

Is your convention different?

You could throw the action in an Organizer and just invoke it that way. Would that work for you?

**Comment by alitsiya** [comment]
Thank you @adomokos ! Fair enough, also it would be a duplication of `around_aech`. Happy Holidays! Hope to contribute next year!

**Comment by adomokos** [comment]
Thanks, @alitsiya, same to you! :100:
