### ISSUE TITLE
Namespacing Organizers and Actions

### ISSUE THREAD

**Issue by founder3000** [adomokos/light-service#229]
When I use the generators to create organizers and actions, they place the files under app/actions and app/organizers. However, the modules are not namespaces with those names, and ruby complains about it. Do I need to go in and add 

module Actions

and 

module Organizers

to those files? I'd like for it to work like everything else under apps.

**Comment by adomokos** [comment]
@founder3000 - sorry I have not had a chance to respond earlier. I don't have much experience with generators, as I am not using them.
It seems your question was answered, though, as you closed it.

Feel free to file an issue if something is not working. Proving out it with failing specs would be desirable. Thank you!
