### ISSUE TITLE
Github page

### ISSUE THREAD

**Issue by padi** [adomokos/light-service#57]
Wrote a tentative page using http://github.com/rstacruz/flatdoc.

http://padi.github.io/light-service

Can't seem to make a pull request on a non-existing gh-pages branch

**Comment by adomokos** [comment]
@padi, thank you for that. I'll create a gh-pages branch and please submit a PR. +1 cappuccino for you!

**Comment by adomokos** [comment]
@padi, here is the branch: https://github.com/adomokos/light-service/tree/gh-pages

Would you mind sending a PR? Thank you!

**Comment by padi** [comment]
You may need to create an orphaned gh-pages branch https://help.github.com/articles/creating-project-pages-manually/

**Comment by adomokos** [comment]
@padi, thank you for the info. Can you try it now? http://adomokos.github.io/light-service/ That branch only has an html page.
