### ISSUE TITLE
Rename LightService from light-service to light_service

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#62]
This is the recommended naming pattern. I chose `light-service` based on a blog post I read at the time when I started LightService, but I think now that the name is misleading.

I am not alone with this unique naming convention. The project [RestClient](https://github.com/rest-client/rest-client) follows the same naming convention.

I would be curious to see what other folks are thinking about the possibility of renaming the gem from `light-service` to `light_service`.

**Comment by padi** [comment]
Also noticed this before. Never bothered opening an issue for it, but :+1:

**Comment by ramontayag** [comment]
Yes, `light_service`, since the project isn't `Light::Service`.

**Comment by variousred** [comment]
:+1:

**Comment by adomokos** [comment]
This is actually not all that easy. There is no rename in RubyGems, I have to close the current LightService repo, open up a new one with the new name and continue development on that. Which might make sense as we approach 1.0.

Does anybody else have a simpler, less invasive resolution to this?

**Comment by jeroenvisser101** [comment]
How about making a new one and publishing to both, abandoning (possibly with deprecation warnings to STDOUT) the old?

**Comment by adomokos** [comment]
That's a pretty good idea! Thank you for suggesting that.

**Comment by jeroenvisser101** [comment]
@adomokos thanks — I've not tested that yet, but in theory, it should work.

**Comment by gee-forr** [comment]
Apologies for the bump on an ancient issue, but I would also add a `spec.post_install_message` to the gemspec for the deprecated version.

There are [docs for post_install_message](http://rubygems.rubyforge.org/rubygems-update/Gem/Specification.html) functionality.

**Comment by adomokos** [comment]
I think we know what we want to do with this. I am proposing closing it for now.

**Comment by adomokos** [comment]
I am not sure if we should proceed with this. Closing it, but please reopen if you think this is a must-have.
