### ISSUE TITLE
Allowing aliases for :expects attributes on a LightService::Context object

### ISSUE THREAD

**Issue by rewinfrey** [adomokos/light-service#67]
Let's say we have a generic action that expects a `user` to be supplied in the context.

Later, we create a new Organizer and for the context of that Organizer and its associated Actions, instead of `user` we care about the idea of an `owner`.

However, I want to use the generic action that expects the context to have an `user`. Currently, this causes me to have to create a small, specific action to convert the idea of an `owner` to an `user`:

```ruby
class ExampleAction
  expects :owner
  promises :user

  executed do |context|
    context.user = context.owner
  end
end
```

This can quickly get out of hand though. Alternatively, at the time I create the `owner` object, I could associate it with an `user` at the same time:

```ruby
class ExampleAction2
  expects :params
  promises :owner, :user

  executed do |context|
    context.user = context.owner = User.new(context.params)
  end
end
```

The trouble I have here is that our use of an action in this Organizer requiring an `user` leaks into an action that is really focused on the idea of an `owner`, which means that a more generic action meant to be reused is now leaking into other actions in order to be reused.

I'd like to propose we add the idea of expects aliases to LightService:

```ruby
class ExampleAction3
  expects :user
  alias_context :user, :owner

  executed do |context|
    context.user.behavior!

    # which is equivalent to saying:
    # context.owner.behavior!
  end
end
```

What I hope `ExampleAction3` demonstrates is how LightService can alias an object in the context
with another object in the context, and correctly send messages to the aliased object in the context when the aliased object exists. If there is no aliased object in the context, then `expects` and the context validation works as normal.

**Comment by adomokos** [comment]
:+1: for this feature!

**Comment by jpmoral** [comment]
In my opinion, having the alias in `ExampleAction3` also leaks information that somewhere, some other action passes an `owner` instead of a `user`.  It seems that `ExampleAction3` shouldn't have to know about the other possible names of what it expects.

What do you think of putting such functionality in the organizer?  If we think of actions as self-contained parts, it seems that the organizer should be responsible for making the parts fit together.

**Comment by jpmoral** [comment]
@rewinfrey @adomokos 
Please see my pull request: #68

**Comment by adomokos** [comment]
Thanks @jpmoral! Closing this Issue.
