### ISSUE TITLE
Renaming "context#skip_all!" to "context#skip_rest!" with deprecation

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#76]
As I added documentation for the `context#fail!` and `context#skip_all!` methods, I realized that the name of "skip_all" is misleading. It really should be "skip_rest" or simply "skip" as the organizer is not going to skip all the actions, only the remaining ones.

**Comment by mattr-** [comment]
Another name suggestion: `skip_remaining!`

**Comment by adomokos** [comment]
Renamed in [v 0.8.1](https://github.com/adomokos/light-service/pull/108). Closing it.
