### ISSUE TITLE
`call` interface

### ISSUE THREAD

**Issue by ramontayag** [adomokos/light-service#81]
@adomokos, what do you think about a call interface as well?

```ruby
MyOrganizer.call(1, 2)
MyOrganizer.(1,2) # apparently, you can do this!
```

**Comment by adomokos** [comment]
I've been using the method name `call` for my organizers recently. I open for it.

**Comment by ramontayag** [comment]
Ok you reply fast. Sorry, I just realized - I meant actions. This is useful when making organizer-actions.

**Comment by adomokos** [comment]
How is it useful? Can you provide examples?

**Comment by ramontayag** [comment]
Sometimes, I make an organizer-action that is used in an action, or can be used alone. This will make the code slightly shorter. Also, when testing an action individually, I will be able to invoke `call` or `.()` instead.

It could/should be an alias.

**Comment by adomokos** [comment]
I think that would be a small gain for this change. The convention I've been using is Organizer#call and Action#execute - class level methods. Also, how would the `executed` class level macro look?

**Comment by ramontayag** [comment]
@adomokos - the `executed` macro would be the same. This would be an alias for `Action.execute`.

**Comment by adomokos** [comment]
You could just open the class and add that alias for you through metaprogramming. I don't see this - yet at least - somehting I'd add to LS.

**Comment by ramontayag** [comment]
Yes, I could. Alright - thanks!
