### ISSUE TITLE
Removing Error Codes

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#93]
I am thinking about (deprecating first) and then removing [error codes](https://github.com/adomokos/light-service/#error-codes). I don't think it's widely used, it was added for a specific use case in the past.

Would anybody be against that?

**Comment by mattr-** [comment]
As long as you're talking only about the error codes and keeping the other errors construct, I think thats :+1:. We do a lot of rendering of an `errors` object everywhere at $WORK so it would be useful to be able to continue to use that construct with LightService since I'm trying to sneak it into the codebase in places. :smiley:

**Comment by adomokos** [comment]
+1 diet coke when we get together next time - for using LS!

I would keep everything else for errors. We should have just used a project specific monkey-patch for error codes, imho. That's what we do now when we want to "add" behavior that might not be a good fit for LS.

**Comment by mattr-** [comment]
Cool. kill it with :fire: then. :smiley:

**Comment by nicolas-besnard** [comment]
@adomokos I'm using error_code for flow control, and the `message` for the flash message. But I'm maybe using it the wrong way

**Comment by adomokos** [comment]
@nicolas-besnard: that wasn't the intent for the error codes. Do you have a code sample we could take a look at? Maybe there would be another way to do it.

**Comment by nicolas-besnard** [comment]
Basically, I'm doing:

```ruby
class MyService
  executed do |context|
    if context.foo
      context.fail!(:error_foo, :error_foo)
      next context
    end

    if context.bar
      context.fail!(:error_bar, :error_bar)
      next context
    end
  end
end
``` 

And in my controller

```ruby
class ServiceController
  def index
    service = MyService.execute

    if service.success?
      redirect_to somewhere_path
    elsif service.error_code == :error_foo
      redirect_to somewhere_else_path
    end
  end
end
```

**Comment by adomokos** [comment]
I see, thanks for the example.

I tried to see how I would refactor this example without the error code, this is what I came up with:

```ruby
class MyService
  promises :error_code

  executed do |context|
    if context.foo
      context.error_code = :error_foo
      context.fail!
      next context
    end

    if context.bar
      context.error_code = :error_bar
      context.fail!
      next context
    end
  end
end
```

And your controller code could be the same:

```ruby
class ServiceController
  def index
    service_result = MyService.execute

    if service_result.success?
      redirect_to somewhere_path
    elsif service_result.error_code == :error_foo
      redirect_to somewhere_else_path
    end
  end
end
```

I can see it beeing not as nifty as the one you had, where the `fail!` call set the error code as well. But you are using it properly, error code was added to get more granular with failures.

I am thinking if we need an error context (maybe as simple as a hash) for better error responses.

What if the default case would be `fail!(message)`, but we would allow passing in an extra hash if you want more information about the failure: `fail!(message, { :error_code => :error_foo })`.
Then, in the caller, you could extract that information like this:

```ruby
class ServiceController
  def index
    service_result = MyService.execute

    if service_result.success?
      redirect_to somewhere_path
      return
    end

    error_code = service_result.error_context[:error_code]

    raise "no error_code was provided" unless error_code

    if error_code == :error_foo
      redirect_to somewhere_error_foo_path
      return
    end

    if error_code == :error_foo
      redirect_to somewhere_error_foo_path
      return
    end
  end
end
```

I am not sure I like this, there is way too much ceremony to get the error code out.

I noticed you are calling fail with two arguments, as the first argument is the user readable message, and the second is the error code. Why not combining both? So if you want to set a message, just do this `ctx.fail!('An error occurred')`, or if you want to use an error code, just use a symbol: `ctx.fail!(:error_foo)`.

Right now you need to call `ctx.message` to get the message out, I think you could use that field to pull the error code.

```ruby
class ServiceController
  def index
    service_result = MyService.execute

    if service_result.success?
      redirect_to somewhere_path
      return
    end

    error_code = service_result.message

    raise "no error_code was provided" unless error_code

    if error_code == :error_foo
      redirect_to somewhere_error_foo_path
      return
    end

    if error_code == :error_foo
      redirect_to somewhere_error_foo_path
      return
    end
  end
end
```

I don't really like to calll `ctx.message` to get the error_code from the context as it's blurry and feels like a hack, but I prefer this solution over the other one with the extra hash for error context.

The third option would be similar to what Golang offers: we could return a tuple with `[error, result]` from an Action or Organizer call, where the error would be a full, extensible object to add more custom errors and result would be the result context. I am not sure I am ready to go there just yet.

**Comment by nicolas-besnard** [comment]
For most of my personal case, I'm using the same error_code as my I18n key

```ruby
context.fail!(:foo, :foo)
# or
context.fail!(:foo, { error_code: :foo, value: :bar })
```

It might be a solution to set the `error_code` when setting the first argument of `fail!`, but you couldn't use a string anymore.

**Comment by adomokos** [comment]
I wonder if there is a more generic way to handle this. Does anybody have a better idea than using error codes?

**Comment by gee-forr** [comment]
I've actually been using error codes to represent HTTP 4xx or 5xx response codes under different error conditions.

I see it as a really valuable feature.

I'd like to add a -1 to deprecating this feature.

**Comment by adomokos** [comment]
K, I am closing this issue for now then. We started some work on instrumentation, I wonder if it could be a major feature.
