### ISSUE TITLE
Allows custom key on context

### ISSUE THREAD

**Issue by nicolas-besnard** [adomokos/light-service#96]
Sometimes, I'd like to be able to add custom key on the context especially when you have condition in your service. 

Example: 

```ruby
class Contributions::Create
  extend LightService::Action

  expects :contribution, :user
  promises :redirect_to

  executed do |context|

    if context.contribution.wire_transfer?
      service = CreateWithWireTransfer.for_project

      if service.success?
        context.redirect_to = nil # <= I'd like to be able to not set this
      else
        context.fail!(service.message, service.error_code)
      end
    elsif context.contribution.credit_card?
      service = CreateWithCreditCard.for_project

      if service.success?
        context.redirect_to = service.redirect_to
      else
        context.fail!(service.message, service.error_code)
      end
    end
  end
end
```

**Comment by adomokos** [comment]
The idea behind `promises` was that you have to set a value for the promised key in the context. There is no observer set on the `promises` and `expects` collection, you had to explicitly set it to `nil` if that's what the value should be. This was the simplest solution, although I have to say, it might not be the best.

Here is how I would express that logic you described there:

```ruby
class Contributions::Create
  extend LightService::Action

  expects :contribution, :user
  promises :redirect_to

  executed do |context|
    context.redirect_to = nil # Set it to nil immediately

    if context.contribution.wire_transfer?
      service = CreateWithWireTransfer.for_project
      next context if context.success?
    end

    if context.contribution.credit_card?
      service = CreateWithCreditCard.for_project
    end

    if service.failure?
      context.fail!(service.message, service.error_code)
    end

    context.redirect_to = service.redirect_to
  end
end
```

Conditionals are increasing complexity, I try to deal with them sparingly. Nested conditionals are hard to reason about, I try to structure the code like the one above, using guards and exit points.

I set the `context.redirect_to` to nil, this is my default case, if nothing else touches that, I know this is the value I get.

Also, I suspect you might be calling an Organizer from an Action which we are trying to avoid. That can lead to spaghetti code, where you have to dig pretty deep to find out what your code is doing. I try to use Organizers to "tell me the story", so I don't have to go deep to find the actual procedure I need to change.

Hope this helps!
